receivers:
  otlp:
    protocols:
      http:
      grpc: {}

processors:
  batch:
exporters:
  logging:
    logLevel: info
  otlphttp:
    endpoint: "http://jaeger:4318"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
