# QuestionWork -- Auto-Fix Common Issues
# Automatically detects and fixes the most frequent problems

$ErrorActionPreference = "SilentlyContinue"

$ROOT         = Split-Path -Parent $PSScriptRoot
$BACKEND_DIR  = Join-Path $ROOT "backend"
$FRONTEND_DIR = Join-Path $ROOT "frontend"

$fixCount  = 0
$skipCount = 0
$failCount = 0

# ─── Helpers ─────────────────────────────────────────────────────────────────

function Write-Section {
    param([string]$Title)
    Write-Host ""
    Write-Host "  +---------------------------------------------+" -ForegroundColor Cyan
    Write-Host ("  |  " + $Title.PadRight(43) + "|") -ForegroundColor Cyan
    Write-Host "  +---------------------------------------------+" -ForegroundColor Cyan
    Write-Host ""
}

function Write-Fixed {
    param([string]$Msg, [string]$Detail = "")
    $script:fixCount++
    Write-Host "  [FIXED] $Msg" -ForegroundColor Green -NoNewline
    if ($Detail) { Write-Host "  =>  $Detail" -ForegroundColor DarkGray } else { Write-Host "" }
}

function Write-Skip {
    param([string]$Msg, [string]$Detail = "")
    $script:skipCount++
    Write-Host "  [SKIP]  $Msg" -ForegroundColor Gray -NoNewline
    if ($Detail) { Write-Host "  =>  $Detail" -ForegroundColor DarkGray } else { Write-Host "" }
}

function Write-Err {
    param([string]$Msg, [string]$Detail = "")
    $script:failCount++
    Write-Host "  [ERROR] $Msg" -ForegroundColor Red -NoNewline
    if ($Detail) { Write-Host "  =>  $Detail" -ForegroundColor DarkGray } else { Write-Host "" }
}

function Write-Info {
    param([string]$Msg)
    Write-Host "    [INFO] $Msg" -ForegroundColor DarkGray
}

function Test-Port {
    param([int]$Port)
    $conn = Test-NetConnection -ComputerName 127.0.0.1 -Port $Port `
                -WarningAction SilentlyContinue -ErrorAction SilentlyContinue
    return $conn.TcpTestSucceeded
}

# ─── Header ──────────────────────────────────────────────────────────────────

Clear-Host
Write-Host ""
Write-Host "  =============================================" -ForegroundColor Yellow
Write-Host "   QuestionWork -- Auto-Fix Common Issues"      -ForegroundColor Yellow
Write-Host "   $(Get-Date -Format 'yyyy-MM-dd  HH:mm:ss')"  -ForegroundColor Yellow
Write-Host "  =============================================" -ForegroundColor Yellow
Write-Host ""
Write-Host "  This script will scan for common problems and fix them automatically." -ForegroundColor Gray
Write-Host "  No destructive changes will be made without confirmation." -ForegroundColor Gray
Write-Host ""

# ===========================================================================
Write-Section "FIX 1: Backend .env file"
# ===========================================================================

$backendEnvPath = Join-Path $BACKEND_DIR ".env"

if (Test-Path $backendEnvPath) {
    Write-Skip "backend\.env already exists"
} else {
    Write-Host "  [WARN] backend\.env is missing -- creating with defaults..." -ForegroundColor Yellow

    $secretKey = -join ((65..90) + (97..122) + (48..57) + @(45,95) |
                  Get-Random -Count 48 | ForEach-Object { [char]$_ })

    $envContent = @"
# QuestionWork Backend Configuration
# Generated by fix-common-issues.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

# Application
APP_NAME=QuestionWork
APP_ENV=development
DEBUG=True
SECRET_KEY=$secretKey

# Server
HOST=127.0.0.1
PORT=8000

# Database (PostgreSQL) -- not yet connected, using in-memory storage
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/questionwork
REDIS_URL=redis://localhost:6379

# JWT Settings
JWT_ALGORITHM=HS256
JWT_EXPIRE_MINUTES=30

# CORS (Frontend URL)
FRONTEND_URL=http://localhost:3000

# OpenRouter API (for AI skill verification -- optional)
OPENROUTER_API_KEY=your-api-key-here
OPENROUTER_MODEL=qwen/qwen-2.5-coder-32b-instruct
"@

    try {
        Set-Content -Path $backendEnvPath -Value $envContent -Encoding UTF8
        Write-Fixed "Created backend\.env" "SECRET_KEY auto-generated"
    } catch {
        Write-Err "Failed to create backend\.env" $_.Exception.Message
    }
}

# Validate existing .env has required keys
if (Test-Path $backendEnvPath) {
    $envContent = Get-Content $backendEnvPath -Raw -Encoding UTF8

    $requiredKeys = @("SECRET_KEY", "FRONTEND_URL", "JWT_ALGORITHM", "DATABASE_URL", "REDIS_URL")
    foreach ($key in $requiredKeys) {
        if ($envContent -notmatch "$key=") {
            Write-Host "  [WARN] backend\.env is missing key: $key" -ForegroundColor Yellow
            # Append missing key with default
            switch ($key) {
                "SECRET_KEY"    { Add-Content $backendEnvPath "`nSECRET_KEY=change-me-please-update-this" }
                "FRONTEND_URL"  { Add-Content $backendEnvPath "`nFRONTEND_URL=http://localhost:3000" }
                "JWT_ALGORITHM" { Add-Content $backendEnvPath "`nJWT_ALGORITHM=HS256" }
                "DATABASE_URL"  { Add-Content $backendEnvPath "`nDATABASE_URL=postgresql://postgres:postgres@localhost:5432/questionwork" }
                "REDIS_URL"     { Add-Content $backendEnvPath "`nREDIS_URL=redis://localhost:6379" }
            }
            Write-Fixed "Appended missing key to backend\.env" $key
        }
    }
}

# ===========================================================================
Write-Section "FIX 2: Frontend .env.local file"
# ===========================================================================

$frontendEnvPath = Join-Path $FRONTEND_DIR ".env.local"

if (Test-Path $frontendEnvPath) {
    $feEnv = Get-Content $frontendEnvPath -Raw -Encoding UTF8
    if ($feEnv -match "NEXT_PUBLIC_API_URL=") {
        Write-Skip "frontend\.env.local already has NEXT_PUBLIC_API_URL"
    } else {
        Add-Content $frontendEnvPath "`nNEXT_PUBLIC_API_URL=http://localhost:8000/api/v1"
        Write-Fixed "Appended NEXT_PUBLIC_API_URL to frontend\.env.local"
    }
} else {
    $feEnvContent = @"
# QuestionWork Frontend Environment
# Generated by fix-common-issues.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

# Backend API URL
NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
"@
    try {
        Set-Content -Path $frontendEnvPath -Value $feEnvContent -Encoding UTF8
        Write-Fixed "Created frontend\.env.local" "NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1"
    } catch {
        Write-Err "Failed to create frontend\.env.local" $_.Exception.Message
    }
}

# ===========================================================================
Write-Section "FIX 3: Python virtual environment"
# ===========================================================================

$venvPath     = Join-Path $BACKEND_DIR ".venv"
$venvActivate = Join-Path $venvPath "Scripts\activate.ps1"
$venvPython   = Join-Path $venvPath "Scripts\python.exe"

if (Test-Path $venvPython) {
    Write-Skip "Python venv already exists" $venvPath
} else {
    Write-Host "  [WARN] Python venv not found -- creating..." -ForegroundColor Yellow

    # Check if Python is available
    $pythonCmd = $null
    foreach ($cmd in @("python", "python3", "py")) {
        try {
            $ver = & $cmd --version 2>&1
            if ($LASTEXITCODE -eq 0) {
                $pythonCmd = $cmd
                break
            }
        } catch {}
    }

    if ($pythonCmd) {
        Write-Info "Using Python: $pythonCmd"
        Push-Location $BACKEND_DIR
        try {
            & $pythonCmd -m venv .venv 2>&1 | Out-Null
            if (Test-Path $venvPython) {
                Write-Fixed "Python venv created" $venvPath
            } else {
                Write-Err "Venv creation failed" "Check Python installation"
            }
        } catch {
            Write-Err "Venv creation error" $_.Exception.Message
        }
        Pop-Location
    } else {
        Write-Err "Python not found in PATH" "Install Python 3.10+ from python.org"
    }
}

# ===========================================================================
Write-Section "FIX 4: Backend Python dependencies"
# ===========================================================================

$requirementsPath = Join-Path $BACKEND_DIR "requirements.txt"
$venvPip          = Join-Path $venvPath "Scripts\pip.exe"

if (-not (Test-Path $venvPip)) {
    Write-Skip "pip not found — venv may not be set up" "Run: python -m venv .venv in backend/"
} elseif (-not (Test-Path $requirementsPath)) {
    Write-Err "requirements.txt not found" $requirementsPath
} else {
    # Check if fastapi is installed
    $fastapiPath = Get-ChildItem (Join-Path $venvPath "Lib\site-packages") -Filter "fastapi*" `
                       -Directory -ErrorAction SilentlyContinue | Select-Object -First 1

    if ($fastapiPath) {
        Write-Skip "Backend packages already installed" "fastapi found at $($fastapiPath.FullName)"
    } else {
        Write-Host "  [WARN] Backend packages not installed -- running pip install..." -ForegroundColor Yellow
        Push-Location $BACKEND_DIR
        try {
            & $venvPip install -r requirements.txt --quiet 2>&1
            if ($LASTEXITCODE -eq 0) {
                Write-Fixed "Backend packages installed" "pip install -r requirements.txt"
            } else {
                Write-Err "pip install failed" "Check requirements.txt and internet connection"
            }
        } catch {
            Write-Err "pip install error" $_.Exception.Message
        }
        Pop-Location
    }
}

# ===========================================================================
Write-Section "FIX 5: Frontend npm dependencies"
# ===========================================================================

$nodeModulesPath = Join-Path $FRONTEND_DIR "node_modules"
$nextBinPath     = Join-Path $nodeModulesPath ".bin\next"
$packageJsonPath = Join-Path $FRONTEND_DIR "package.json"

if (-not (Test-Path $packageJsonPath)) {
    Write-Err "package.json not found" $FRONTEND_DIR
} elseif (Test-Path $nextBinPath) {
    Write-Skip "Frontend packages already installed" "next binary found"
} else {
    Write-Host "  [WARN] node_modules missing -- running npm install..." -ForegroundColor Yellow

    # Check if npm is available
    try {
        $npmVer = npm --version 2>&1
        $npmOk  = ($LASTEXITCODE -eq 0)
    } catch {
        $npmOk = $false
    }

    if ($npmOk) {
        Push-Location $FRONTEND_DIR
        try {
            npm install --silent 2>&1 | Out-Null
            if (Test-Path $nextBinPath) {
                Write-Fixed "Frontend packages installed" "npm install completed"
            } else {
                Write-Err "npm install may have failed" "Check internet connection and package.json"
            }
        } catch {
            Write-Err "npm install error" $_.Exception.Message
        }
        Pop-Location
    } else {
        Write-Err "npm not found in PATH" "Install Node.js from nodejs.org"
    }
}

# ===========================================================================
Write-Section "FIX 6: Kill processes on busy ports"
# ===========================================================================

function Clear-Port {
    param([int]$Port, [string]$ServiceName)

    if (Test-Port $Port) {
        Write-Host "  [INFO] Port $Port is in use ($ServiceName may be running)" -ForegroundColor DarkGray
        Write-Skip "Port $Port" "already in use — not killing (may be intentional)"
    } else {
        Write-Skip "Port $Port is free" "nothing to do"
    }
}

Clear-Port 8000 "Backend (uvicorn)"
Clear-Port 3000 "Frontend (Next.js)"

# ===========================================================================
Write-Section "FIX 7: PowerShell execution policy"
# ===========================================================================

$policy = Get-ExecutionPolicy -Scope CurrentUser
if ($policy -eq "Restricted" -or $policy -eq "AllSigned") {
    Write-Host "  [WARN] PowerShell execution policy is '$policy'" -ForegroundColor Yellow
    Write-Host "         Scripts cannot run -- attempting to fix..." -ForegroundColor Gray

    try {
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
        Write-Fixed "Execution policy set to RemoteSigned (CurrentUser scope)"
    } catch {
        Write-Err "Could not change execution policy" "Run manually: Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"
    }
} else {
    Write-Skip "Execution policy is '$policy'" "scripts can run"
}

# ===========================================================================
Write-Section "FIX 8: Windows console UTF-8 encoding"
# ===========================================================================

$currentCP = [Console]::OutputEncoding.CodePage
if ($currentCP -ne 65001) {
    Write-Host "  [WARN] Console encoding is CP$currentCP (not UTF-8 / CP65001)" -ForegroundColor Yellow
    try {
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $OutputEncoding           = [System.Text.Encoding]::UTF8
        chcp 65001 2>&1 | Out-Null
        Write-Fixed "Console encoding set to UTF-8 (CP65001)" "for this session only"
        Write-Info "To make permanent, add to PowerShell profile: [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()"
    } catch {
        Write-Err "Could not set UTF-8 encoding" $_.Exception.Message
    }
} else {
    Write-Skip "Console encoding is already UTF-8 (CP65001)"
}

# ===========================================================================
Write-Section "FIX 9: Docker -- start Redis container"
# ===========================================================================

try {
    $dockerInfo = docker info 2>&1
    $dockerOk   = ($LASTEXITCODE -eq 0)
} catch {
    $dockerOk = $false
}

if (-not $dockerOk) {
    Write-Skip "Docker not running" "start Docker Desktop manually if you need Redis"
} else {
    $containers   = docker ps --format "{{.Names}}" 2>&1
    $redisRunning = ($containers | Where-Object { $_ -like "*questionwork-redis*" }).Count -gt 0
    $allContainers = docker ps -a --format "{{.Names}}" 2>&1
    $redisExists  = ($allContainers | Where-Object { $_ -like "*questionwork-redis*" }).Count -gt 0

    if ($redisRunning) {
        Write-Skip "questionwork-redis container is already running"
    } elseif ($redisExists) {
        Write-Host "  [WARN] questionwork-redis exists but is stopped -- starting..." -ForegroundColor Yellow
        docker start questionwork-redis 2>&1 | Out-Null
        Start-Sleep -Seconds 2
        $nowRunning = (docker ps --format "{{.Names}}" 2>&1) -like "*questionwork-redis*"
        if ($nowRunning) {
            Write-Fixed "Started questionwork-redis container"
        } else {
            Write-Err "Failed to start questionwork-redis"
        }
    } else {
        Write-Host "  [WARN] questionwork-redis container not found -- creating..." -ForegroundColor Yellow
        docker run -d --name questionwork-redis -p 6379:6379 redis:7-alpine 2>&1 | Out-Null
        Start-Sleep -Seconds 3
        $nowRunning = (docker ps --format "{{.Names}}" 2>&1) -like "*questionwork-redis*"
        if ($nowRunning) {
            Write-Fixed "Created and started questionwork-redis (Redis 7 Alpine)"
        } else {
            Write-Err "Failed to create Redis container" "Check Docker and internet connection"
        }
    }
}

# ===========================================================================
Write-Section "FIX 10: Verify backend app structure"
# ===========================================================================

$criticalFiles = @(
    @{ Path = "backend\app\main.py";                        Label = "Backend main.py" },
    @{ Path = "backend\app\api\v1\api.py";                  Label = "API router" },
    @{ Path = "backend\app\api\v1\endpoints\auth.py";       Label = "Auth endpoint" },
    @{ Path = "backend\app\api\v1\endpoints\quests.py";     Label = "Quests endpoint" },
    @{ Path = "backend\app\api\v1\endpoints\users.py";      Label = "Users endpoint" },
    @{ Path = "backend\app\core\security.py";               Label = "Security (JWT)" },
    @{ Path = "backend\app\core\rewards.py";                Label = "Rewards (XP)" },
    @{ Path = "backend\app\models\user.py";                 Label = "User models" },
    @{ Path = "backend\app\models\quest.py";                Label = "Quest models" },
    @{ Path = "frontend\src\app\page.tsx";                  Label = "Homepage" },
    @{ Path = "frontend\src\app\auth\login\page.tsx";       Label = "Login page" },
    @{ Path = "frontend\src\app\auth\register\page.tsx";    Label = "Register page" },
    @{ Path = "frontend\src\app\quests\page.tsx";           Label = "Quests list" },
    @{ Path = "frontend\src\app\quests\create\page.tsx";    Label = "Create quest" },
    @{ Path = "frontend\src\app\quests\[id]\page.tsx";      Label = "Quest detail" },
    @{ Path = "frontend\src\app\marketplace\page.tsx";      Label = "Marketplace" },
    @{ Path = "frontend\src\app\profile\page.tsx";          Label = "Profile page" },
    @{ Path = "frontend\src\context\AuthContext.tsx";       Label = "AuthContext" },
    @{ Path = "frontend\src\lib\api.ts";                    Label = "API client" }
)

$missingFiles = @()
foreach ($file in $criticalFiles) {
    $fullPath = Join-Path $ROOT $file.Path
    if (Test-Path $fullPath) {
        Write-Skip "$($file.Label) exists"
    } else {
        Write-Err "$($file.Label) is MISSING" $file.Path
        $missingFiles += $file
    }
}

if ($missingFiles.Count -gt 0) {
    Write-Host ""
    Write-Host "  [ACTION REQUIRED] $($missingFiles.Count) critical file(s) are missing!" -ForegroundColor Red
    Write-Host "  These cannot be auto-created — check git history or restore from backup." -ForegroundColor Yellow
}

# ===========================================================================
Write-Section "FIX 11: __init__.py files for Python packages"
# ===========================================================================

$initDirs = @(
    "backend\app",
    "backend\app\api",
    "backend\app\api\v1",
    "backend\app\api\v1\endpoints",
    "backend\app\core",
    "backend\app\models",
    "backend\app\db",
    "backend\app\schemas",
    "backend\app\services"
)

foreach ($dir in $initDirs) {
    $dirPath  = Join-Path $ROOT $dir
    $initPath = Join-Path $dirPath "__init__.py"

    if (-not (Test-Path $dirPath)) {
        try {
            New-Item -ItemType Directory -Path $dirPath -Force | Out-Null
            Write-Fixed "Created missing directory" $dir
        } catch {
            Write-Err "Could not create directory" $dir
        }
    }

    if (Test-Path $dirPath) {
        if (Test-Path $initPath) {
            Write-Skip "__init__.py exists in $dir"
        } else {
            try {
                Set-Content -Path $initPath -Value "" -Encoding UTF8
                Write-Fixed "Created __init__.py" $dir
            } catch {
                Write-Err "Could not create __init__.py in $dir" $_.Exception.Message
            }
        }
    }
}

# ===========================================================================
Write-Section "FIX 12: Quick backend syntax check"
# ===========================================================================

$venvPythonExe = Join-Path $venvPath "Scripts\python.exe"

if (Test-Path $venvPythonExe) {
    $filesToCheck = @(
        "app\main.py",
        "app\api\v1\api.py",
        "app\api\v1\endpoints\auth.py",
        "app\api\v1\endpoints\quests.py",
        "app\api\v1\endpoints\users.py",
        "app\core\security.py",
        "app\core\rewards.py"
    )

    Push-Location $BACKEND_DIR
    $syntaxErrors = 0
    foreach ($pyFile in $filesToCheck) {
        $fullPath = Join-Path $BACKEND_DIR $pyFile
        if (Test-Path $fullPath) {
            $result = & $venvPythonExe -m py_compile $pyFile 2>&1
            if ($LASTEXITCODE -eq 0) {
                Write-Skip "Syntax OK: $pyFile"
            } else {
                Write-Err "Syntax ERROR in $pyFile" $result
                $syntaxErrors++
            }
        } else {
            Write-Skip "Not found (skipping): $pyFile"
        }
    }
    Pop-Location

    if ($syntaxErrors -eq 0) {
        Write-Host "    All Python files passed syntax check." -ForegroundColor Green
    } else {
        Write-Host "    $syntaxErrors file(s) have syntax errors — fix manually." -ForegroundColor Red
    }
} else {
    Write-Skip "Python venv not available" "skipping syntax check"
}

# ===========================================================================
# Summary
# ===========================================================================

Write-Host ""
Write-Host "  =============================================" -ForegroundColor Yellow
Write-Host ""
Write-Host "  SUMMARY" -ForegroundColor White
Write-Host ""
Write-Host "    Fixed   : $fixCount" -ForegroundColor Green
Write-Host "    Skipped : $skipCount (already OK)" -ForegroundColor Gray
Write-Host "    Errors  : $failCount" -ForegroundColor $(if ($failCount -gt 0) { "Red" } else { "Gray" })
Write-Host ""

if ($failCount -gt 0) {
    Write-Host "  Some issues could not be auto-fixed. Manual steps needed:" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  1. Install Python 3.10+   : https://www.python.org/downloads/" -ForegroundColor Gray
    Write-Host "  2. Install Node.js 18+    : https://nodejs.org/" -ForegroundColor Gray
    Write-Host "  3. Install Docker Desktop : https://www.docker.com/products/docker-desktop/" -ForegroundColor Gray
    Write-Host "  4. Restore missing files  : check git history" -ForegroundColor Gray
    Write-Host ""
} elseif ($fixCount -gt 0) {
    Write-Host "  All fixable issues have been resolved!" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Next step — start the project:" -ForegroundColor Cyan
    Write-Host "    .\scripts\start-all.ps1" -ForegroundColor White
    Write-Host ""
} else {
    Write-Host "  Everything looks good — no fixes needed!" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Run the project:" -ForegroundColor Cyan
    Write-Host "    .\scripts\start-all.ps1" -ForegroundColor White
    Write-Host ""
}

Write-Host "  Full status check:" -ForegroundColor Gray
Write-Host "    .\scripts\check-status.ps1" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  E2E test:" -ForegroundColor Gray
Write-Host "    .\scripts\test-flow.ps1" -ForegroundColor DarkGray
Write-Host ""
